language: node_js
node_js:
  - 9.11.2

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

before_script:
  - git remote set-url origin https://${GITHUB_TOKEN}@github.com/pie-framework/pie-ui.git

stages:
  - name: build-and-deploy-dev
    if: branch = develop
  - name: travis-release-deploy
    if: branch = master
jobs:
  include:
    - stage: build-and-deploy-dev
      script: 'npm run build:demo && npm run deploy:demo:dev'
    - stage: travis-release-deploy
      script: 'scripts/travis-release-deploy'

branches:
  only:
    - develop
    - master
cache:
  yarn: true
  directories:
    - node_modules
