version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:11.10.0

reg_auth: &reg_auth
  name: Authenticate with registry
  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

restore_cache: &restore_cache
  keys:
    - v1-dependencies-{{ checksum "package.json" }}
    # fallback to using the latest cache if no exact match is found
    - v1-dependencies-

save_cache: &save_cache
  paths:
    - node_modules
  key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - run: *reg_auth
      - restore_cache: *restore_cache
      - run: yarn install
      - save_cache: *save_cache
      - run: scripts/build release --next --skipForcePublish

  deploy_demo:
    <<: *defaults

    steps:
      - checkout
      - run: *reg_auth
      - restore_cache: *restore_cache
      - run: yarn install
      - save_cache: *save_cache
      - run: scripts/build build buildDemo deployDemo --next

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop

  nightly:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - develop
    jobs:
      - deploy_demo
